### ISSUE TITLE
fcgi and woo

### ISSUE THREAD

**Issue by knobo** [fukamachi/websocket-driver#4]
Are there anything I can do to make ti work with woo of fcgi?

When I tried with fgi I got:

NIL fell through ETYPECASE expression.
Wanted one of (CL-ASYNC:SOCKET IOLIB.SOCKETS:SOCKET).

  0: (SB-KERNEL:CASE-FAILURE ETYPECASE NIL (CL-ASYNC:SOCKET IOLIB.SOCKETS:SOCKET))
      Locals:
        SB-DEBUG::ARG-0 = ETYPECASE
        SB-DEBUG::ARG-1 = NIL
        SB-DEBUG::ARG-2 = (CL-ASYNC:SOCKET IOLIB.SOCKETS:SOCKET)
  1: (WEBSOCKET-DRIVER.DRIVER.BASE:SET-READ-CALLBACK #<WEBSOCKET-DRIVER.DRIVER.HYBI:HYBI {1005712E43}> #<CLOSURE (LAMBDA (WEBSOCKET-DRIVER.DRIVER.BASE::DATA) :IN WEBSOCKET-DRIVER.DRIVER.BASE:START-CONNECTI..
      Locals:
        SB-DEBUG::ARG-0 = #<WEBSOCKET-DRIVER.DRIVER.HYBI:HYBI {1005712E43}>
        SB-DEBUG::ARG-1 = #<CLOSURE (LAMBDA (WEBSOCKET-DRIVER.DRIVER.BASE::DATA) :IN WEBSOCKET-DRIVER.DRIVER.BASE:START-CONNECTION) {100571492B}>

**Comment by fukamachi** [comment]
This library requires that the `ENV` has a socket in `:clack.io`, but FastCGI and Woo doesn't let access to it.

**Comment by fukamachi** [comment]
It cannot support FastCGI because its protocol isn't made for persistent connections like WebSocket.

Woo can be supported and I quickly implemented in the [woo](https://github.com/fukamachi/websocket-driver/tree/woo) branch, but it actually adds "woo" as a dependency and which means this requires both of "libuv" and "libev" if we use only one of "wookie" or "woo". I'll do some more later.

**Comment by knobo** [comment]
Thank you, it works :)

**Comment by fukamachi** [comment]
It has been merged.

**Comment by knobo** [comment]
Thank you :)
